Bugfix: Creating TAP-Port netelement not possible.
Fixes
prod.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: ""

The validaton crashed when ID NULL was inserted – the resulting validator rule
looked like
"address1" => "required|unique:netelement,address1,,id,deleted_at,NULL,netelementtype_id,9|regex:/^([0-9A-F]{2}){4}(~\d)?$/"
Now we get
"address1" => "required|unique:netelement,address1,0,id,deleted_at,NULL,netelementtype_id,9|regex:/^([0-9A-F]{2}){4}(~\d)?$/"
instead.