Bugfix: Store empty string to col value in radcheck instead of null.
This fixes
prod.ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "value" of relation "radcheck" violates not-null constraint