Adapt browser settings to make DocumentManagement work again.
@walirazzaq I needed to make this changes to be able to create
documents.
Otherwise I got an error:
```
local.ERROR: Chrome process stopped before startup completed. Additional info: chrome_crashpad_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.
[2568435:2568435:0204/161009.515982:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104) {"userId":1,"exception":"[object] (RuntimeException(code: 0): Chrome process stopped before startup completed. Additional info: chrome_crashpad
_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.
[2568435:2568435:0204/161009.515982:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104) at /var/www/nmsprime/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:427)
```

Changing Browser.php and updating chromium solved the problem.